### ISSUE TITLE
Help (Crash Report)

### ISSUE THREAD

**Issue by REALHaydenGaming** [BeastlyGhost/Forever-Engine-Feather#16]
**Information:**
Linux (Chrome OS Extentsions, Wine)
2 GBs of storage LEFT on said Linux (Folder)
Github Commit Build (Atleast a day from now as of writing).

After I tested an event, it just started crashing all of a sudden.
![Screenshot 2022-11-26 2 35 45 PM](https://user-images.githubusercontent.com/107285739/204106274-35fd9c8e-e95e-4a41-8425-fe68bec466dc.png)
And I didn't even put the event on anywhere.

Any way I can fix this?

**Comment by BeastlyGhost** [comment]
1- you are probably better off compiling **for Linux** instead of using wine, wine can cause problems with scripted events
2- assuming this is the stage change event, your stage is probably invalid

Change Stage also has some problems working with stages, so prior to using it, make sure your stage is *properly* set up

**Comment by BeastlyGhost** [comment]
try compiling or downloading a version for your system instead of using wine, as it commonly causes problems

**Comment by BeastlyGhost** [comment]
closing since this is technically solved(??)
